include:
  - ../compose.common.yaml

services:
  soju:
    container_name: soju
    read_only: true
    build:
      context: .
    ports:
      - 6697:6697

    volumes:
      - ./config/soju.config:/etc/soju/config:ro
      - ./state:/state:rw
      - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/cert/priv.pem:ro
      - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/cert/cert.pem:ro

    networks:
      - main

    restart: unless-stopped
